const buttons = [
  {
    key: "1",
    display: "CA",
    id: "clear",
    className: "button button--clear",
    dispatchIndicator: "CLEAR",
  },
  {
    key: "2",
    display: "/",
    id: "divide",
    className: "button button--operator",
    dispatchIndicator: "OPERATOR",
  },
  {
    key: "3",
    display: "*",
    id: "multiply",
    className: "button button--operator",
    dispatchIndicator: "OPERATOR",
  },
  {
    key: "4",
    display: "7",
    id: "seven",
    className: "button button--number",
    dispatchIndicator: "DIGIT",
  },
  {
    key: "5",
    display: "8",
    id: "eight",
    className: "button button--number",
    dispatchIndicator: "DIGIT",
  },
  {
    key: "6",
    display: "9",
    id: "nine",
    className: "button button--number",
    dispatchIndicator: "DIGIT",
  },
  {
    key: "7",
    display: "-",
    id: "subtract",
    className: "button button--operator",
    dispatchIndicator: "OPERATOR",
  },
  {
    key: "8",
    display: "4",
    id: "four",
    className: "button button--number",
    dispatchIndicator: "DIGIT",
  },
  {
    key: "9",
    display: "5",
    id: "five",
    className: "button button--number",
    dispatchIndicator: "DIGIT",
  },
  {
    key: "10",
    display: "6",
    id: "six",
    className: "button button--number",
    dispatchIndicator: "DIGIT",
  },
  {
    key: "11",
    display: "+",
    id: "add",
    className: "button button--operator",
    dispatchIndicator: "OPERATOR",
  },
  {
    key: "12",
    display: "1",
    id: "one",
    className: "button button--number",
    dispatchIndicator: "DIGIT",
  },
  {
    key: "13",
    display: "2",
    id: "two",
    className: "button button--number",
    dispatchIndicator: "DIGIT",
  },
  {
    key: "14",
    display: "3",
    id: "three",
    className: "button button--number",
    dispatchIndicator: "DIGIT",
  },
  {
    key: "15",
    display: "=",
    id: "equals",
    className: "button button--equals",
    dispatchIndicator: "EQUALS",
  },
  {
    key: "16",
    display: "0",
    id: "zero",
    className: "button button--zero",
    dispatchIndicator: "DIGIT",
  },
  {
    key: "17",
    display: ".",
    id: "decimal",
    className: "button button--decimal",
    dispatchIndicator: "DECIMAL",
  },
];

export default buttons;
